apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clavenar.fullname" . }}-attestation-verifier-contract
  labels:
    {{- include "clavenar.labels" (dict "ctx" . "service" "attestation-verifier-contract") | nindent 4 }}
immutable: true
data:
  attestation-verifier-v1.schema.json: |
{{ .Files.Get "files/attestation-verifier-v1.schema.json" | trimSuffix "\n" | indent 4 }}
  attestation-verifier-v1.fixture.json: |
{{ .Files.Get "files/attestation-verifier-v1.fixture.json" | trimSuffix "\n" | indent 4 }}
