apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clavenar.fullname" . }}-federated-identity-contract
  labels:
    {{- include "clavenar.labels" (dict "ctx" . "service" "federated-identity-contract") | nindent 4 }}
immutable: true
data:
  production-federated-identity-v1.schema.json: |
{{ .Files.Get "files/production-federated-identity-v1.schema.json" | trimSuffix "\n" | indent 4 }}
  production-federated-identity-v1.fixture.json: |
{{ .Files.Get "files/production-federated-identity-v1.fixture.json" | trimSuffix "\n" | indent 4 }}
