apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clavenar.residualProductDispositionConfigMapName" . }}
  labels:
    {{- include "clavenar.labels" (dict "ctx" . "service" "residual-product-disposition") | nindent 4 }}
immutable: true
data:
  residual-product-disposition-v1.schema.json: |
{{ .Files.Get "files/residual-product-disposition-v1.schema.json" | trimSuffix "\n" | indent 4 }}
  residual-product-disposition-v1.fixture.json: |
{{ .Files.Get "files/residual-product-disposition-v1.fixture.json" | trimSuffix "\n" | indent 4 }}
